BigRIPSTSScannor:
  InputFileName: julyTesting/syncTest0007.root
  TreeName: tree
  BranchName: bigrips
#  FirstEntry: 0
#  LastEntry: 1000

ImplantTSScannor:
  InputFileName: julyTesting/extTS_DD.root
  TreeName: PixTree
  PixieBranchName: PixTreeEvent
  MinLowGainDynEnergy: 10000
  MaxLowGainDynEnergy: 65535
#  FirstEntry: 0
#  LastEntry: 1000

BigRIPSImplantMerger:
  OutputFileName: mergedImp.root
  TreeName: mergedImp
  BranchName: mergedImp
  ClassName: OutputTreeData<PixTreeEvent, TreeData>
  TimeWindowLow: 1000
  TimeWindowUp: 1000

MergedImplantTSScannor:
  InputFileName: mergedImp.root
  TreeName: mergedImp
  PixieBranchName: mergedImp
#  FirstEntry: 0
#  LastEntry: 1000

BetaTSScannor:
  InputFileName: julyTesting/extTS_DD.root
  TreeName: PixTree
  PixieBranchName: PixTreeEvent
  MinHighGainDynEnergy: 0
  MaxHighGainDynEnergy: 65535
  MinLowGainDynEnergy: 0
  MaxLowGainDynEnergy: 10000
#  FirstEntry: 0
#  LastEntry: 1000

ImplantBetaMerger:
  OutputFileName: mergedBeta.root
  TreeName: mergedBeta
  BranchName: mergedBeta
  ClassName: OutputTreeData<PixTreeEvent,OutputTreeData<PixTreeEvent, TreeData>>
  TimeWindowLow: 1000
  TimeWindowUp: 1000
