AnamergerMain:
    TreeName: mergedCorrectedBeta
    MergerListName: "./anamergerListGa86.txt"
    NumWorkers: 20
    PrintFrequency: 10000
    UseProof: True
    NumEntries: 30000000
    #FirstEntry: 0
    TimeWindow: 0.5
