AnamergerMain:
    TreeName: mergedImp
    MergerListName: "/home/vandle18/merger/dev/work/mergerList.txt"
    NumWorkers: 4
    #NumEntries: 10000
    #FirstEntry: 0

AnamergerPidSelector:
    ReferenceCutFile: "/home/vandle18/merger/dev/work/referenceCuts.txt"
    OutputFileName: "/home/vandle18/merger/dev/work/anamerger_pid_output.root"

AnamergerVANDLESelector:
    ReferenceCutFile: "/home/vandle18/merger/dev/work/referenceCuts.txt"
    OutputFileName: "/home/vandle18/merger/dev/work/anamerger_vandle_output.root"
