TraceAnalyzer:
    ChannelList:
      - Channel:
          TreeName: "dynode_high"
          SubtypeName: "dynode_high"
          TagName: "ignore"
      - Channel:
          TreeName: "dynode_low"
          SubtypeName: "dynode_low"
          TagName: "ignore"
