BigRIPSTSScannor:
  InputFileName: jul18vandle/syncTest0012.root
  TreeName: tree
  BranchName: bigrips
#  FirstEntry: 0
#  LastEntry: 10000

ImplantTSScannor:
  InputFileName: pixie_rootfiles/extTS_DD.root
  TreeName: PixTree
  PixieBranchName: PixTreeEvent
  MinLowGainDynEnergy: 2000
  MaxLowGainDynEnergy: 65535
#  FirstEntry: 0
#  LastEntry: 10000

BigRIPSImplantMerger:
  OutputFileName: mergedImp.root
  TreeName: mergedImp
  BranchName: mergedImp
  ClassName: OutputTreeData<PixTreeEvent, TreeData>
  TimeWindowLow: 1000
  TimeWindowUp: 1000
  TimeStampScale: 40

MergedImplantTSScannor:
  InputFileName: mergedImp.root
  TreeName: mergedImp
  PixieBranchName: mergedImp
#  FirstEntry: 0
#  LastEntry: 1000

BetaTSScannor:
  InputFileName: pixie_rootfiles/extTS_DD.root
  TreeName: PixTree
  PixieBranchName: PixTreeEvent
  MinHighGainDynEnergy: 10
  MaxHighGainDynEnergy: 30000
  MinLowGainDynEnergy: -2000
  MaxLowGainDynEnergy: 2000
#  FirstEntry: 0
#  LastEntry: 1000

ImplantBetaMerger:
  OutputFileName: mergedBeta.root
  TreeName: mergedBeta
  BranchName: mergedBeta
  ClassName: OutputTreeData<PixTreeEvent,OutputTreeData<PixTreeEvent, TreeData>>
  PrintFrequency: 10
  TimeWindowLow: 1000000000
  TimeWindowUp: 1000000000

BetaImplantMerger:
  OutputFileName: mergedImpBeta.root
  TreeName: mergedImpBeta
  BranchName: mergedImpBeta
  ClassName: OutputTreeData<OutputTreeData<PixTreeEvent, TreeData>,PixTreeEvent>
  PrintFrequency: 10
  TimeWindowLow: 1000000000
  TimeWindowUp: 1000000000
